<a href="https://colab.research.google.com/github/Betancur1991/ModelosMachineLearning/blob/main/Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Primera opción: conjunto de datos 1

1) Fuente de datos

**https://www.kaggle.com/datasets/vuppalaadithyasairam/kidney-stone-prediction-based-on-urine-analysis**

2) Breve descripción de datos

**Contiene datos de analisis de orina para detectar si alguien tiene calculos renales o no**

3) ¿Cuál es el objetivo?

**la deteccion de cálculos renales**

4) ¿Este es un problema de clasificación o regresión?

**Es un problema de clasificación **

5) ¿Cuántas características hay?

**tiene 6 características**

6) ¿Cuántas filas de datos hay?

**tiene 79 filas**

7) ¿Qué retos, si es que hay alguno, prevén en la limpieza, exploración o modelización con este conjunto de datos?

**poder encontrar el mejor modelo para tener la mayor certeza posible en los resultados obtenidos **

Segunda opción: conjunto de datos 2

1) Fuente de datos

**https://www.kaggle.com/datasets/mayzannilarthein44/world-happiness-report-2015-to-2022**

2) Breve descripción de datos

**Contiene datos generales de paises en cuanto a economia, salud, libertad etc y en base a estos datos da un ranking de nivel de felicidad en el pais **

3) ¿Cuál es el objetivo?

**Encontrar un modelo que de acuerdo a estas caracteristicas me diga que tan felices serian las personas bajo dichas condiciones.**

4) ¿Este es un problema de clasificación o regresión?

**es un problema de regresión **

5) ¿Cuántas características hay?

**tiene 10 características**

6) ¿Cuántas filas de datos hay?

**tiene 1229 filas**

7) ¿Qué retos, si es que hay alguno, prevén en la limpieza, exploración o modelización con este conjunto de datos?
**poder encontrar el mejor modelo para tener la mayor certeza posible en los resultados obtenidos para tener un score de felicidad en base a ciertas características **

In [1]:
import pandas as pd

In [2]:
file_calculos='/content/drive/MyDrive/Codificación de Dojo/Modelos/Proyecto/kindey stone urine analysis.csv'

In [3]:
df1=pd.read_csv(file_calculos)
df1.head()

   gravity    ph  osmo  cond  urea  calc  target
0    1.021  4.91   725  14.0   443  2.45       0
1    1.017  5.74   577  20.0   296  4.49       0
2    1.008  7.20   321  14.9   101  2.36       0
3    1.011  5.51   408  12.6   224  2.15       0
4    1.005  6.52   187   7.5    91  1.16       0

In [4]:
file_happines='/content/drive/MyDrive/Codificación de Dojo/Modelos/Proyecto/world-happiness-report-2015-2022-cleaned.csv'

In [5]:
df2=pd.read_csv(file_happines)
df2.head()

,Unnamed: 0,Happiness Rank,Country,Region,Happiness Score,Economy (GDP per Capita),Family (Social Support),Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Year
0,0,1,Switzerland,Western Europe,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2015
1,1,2,Iceland,Western Europe,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.4363,2015
2,2,3,Denmark,Western Europe,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2015
3,3,4,Norway,Western Europe,7.522,1.459,1.33095,0.88521,0.66973,0.36503,0.34699,2015
4,4,5,Canada,North America,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2015